// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismicT from "@prismicio/types";
import type * as prismic from "@prismicio/client";

type Simplify<T> = {
    [KeyType in keyof T]: T[KeyType];
};
/** Content for Speaker documents */
interface SpeakerDocumentData {
    /**
     * Name field in *Speaker*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: speaker.name
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    name: prismicT.KeyTextField;
    /**
     * Role field in *Speaker*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: speaker.role
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    role: prismicT.KeyTextField;
    /**
     * Picture field in *Speaker*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: speaker.picture
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    picture: prismicT.LinkField;
}
/**
 * Speaker document from Prismic
 *
 * - **API ID**: `speaker`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SpeakerDocument<Lang extends string = string> = prismicT.PrismicDocumentWithUID<Simplify<SpeakerDocumentData>, "speaker", Lang>;
export type AllDocumentTypes = SpeakerDocument;
declare module "@prismicio/client" {
    interface CreateClient {
        (repositoryNameOrEndpoint: string, options?: prismic.ClientConfig): prismic.Client<AllDocumentTypes>;
    }
    namespace Content {
        export type { SpeakerDocumentData, SpeakerDocument, AllDocumentTypes };
    }
}
